# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'SIAM&#64;UNR'
tagline:          'The home page'
url:              https://siam-unr.github.io/home 
baseurl:          https://siam-unr.github.io/

# Gems
plugins: [jekyll-paginate,jekyll-gist,pygments]
paginate:         1
paginate_path: "page:num"

# exclude stuff
exclude: [ionicons-2.0.1]
